// Standard country list for seller/listing forms.
export const COUNTRIES: string[] = [
  "United Kingdom",
  "Ireland",
  "France",
  "Germany",
  "Spain",
  "Italy",
  "Netherlands",
  "Belgium",
  "Portugal",
  "Poland",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Austria",
  "Switzerland",
  "Czech Republic",
  "Greece",
  "Hungary",
  "Romania",
  "Bulgaria",
  "Croatia",
  "Slovakia",
  "Slovenia",
  "Lithuania",
  "Latvia",
  "Estonia",
  "Luxembourg",
  "Malta",
  "Cyprus",
  "Iceland",
  "United States",
  "Canada",
  "Australia",
  "New Zealand",
  "Japan",
  "South Korea",
  "China",
  "India",
  "United Arab Emirates",
  "South Africa",
  "Brazil",
  "Mexico",
  "Other",
];

export const DEFAULT_COUNTRY = "United Kingdom";
